/**
 * 契约层 · DTO：Rust 侧 `#[serde(rename_all = "camelCase")]` 结构体的 TS 镜像。
 *
 * 结构体名与 TS 名不同处（历史遗留，改名要动 20+ 个引用文件，收益不抵成本）：
 * `DirEntryInfo → DirEntry`、`PlayerState → MpvPlayerState`。
 * 命令名与参数键名由 `npm run check:ipc` 校验；**字段级**一致性靠这里的注释对照。
 */

// ── 曲库 ────────────────────────────────────────────────────

export interface Track {
  id: string
  name: string
  path: string
  duration: number
  artist: string
  album: string
  format: string
  isVideo: boolean
  coverPath: string | null
  coverData: string | null
  lyricsPath: string | null
  fileMtime: number
  fileSize: number
  metaTitle: string | null
  metaArtist: string | null
  genre: string | null
  bitrate: number | null
  sampleRate: number | null
  loudnessLufs?: number | null
  albumCoverData?: string | null
}

export interface FolderNode {
  name: string
  path: string
  children: FolderNode[]
  tracks: Track[]
  trackCount: number
  coverData: string | null
}

export interface ScanResult {
  folderPaths: string[]
  artists: unknown[]
  folderTree: FolderNode[]
  allTracks: Track[]
  fileCount: number
}

/** Rust: `commands::dialog_fs::DirEntryInfo` */
export interface DirEntry {
  name: string
  isFile: boolean
  isDirectory: boolean
}

export interface PlayProgress {
  trackId: string
  positionMs: number
  completed: boolean
  playCount: number
  playedAt: number
  lastSpeed: number | null
}

export interface Bookmark {
  id: string
  trackId: string
  atMs: number
  label: string
  createdAt: number
}

export interface FavItem {
  id: string
  name: string
  trackIds: string[]
  isDefault?: boolean
  cover?: string
}

// ── 分类与标签（Rust: `taxonomy::{CategoryDto,TagDto,TagSuggestionDto}`）──

export interface Category {
  id: number
  parentId: number | null
  name: string
  icon: string | null
  color: string | null
  sortIndex: number
  trackCount: number
  children: Category[]
}

export interface Tag {
  id: number
  name: string
  color: string | null
  kind: string
  useCount: number
  autoGenerated: boolean
}

export interface TagSuggestion {
  name: string
  score: number
}

// ── 播放内核（libmpv）───────────────────────────────────────

/** Rust: `model::PlayerState` */
export interface MpvPlayerState {
  playing: boolean
  position: number
  duration: number
  speed: number
  volume: number
  muted: boolean
  trackPath: string | null
  videoActive: boolean
  /** 画面显示尺寸（物理像素，含像素长宽比）；0 = 未知。悬浮窗据此锁定窗口比例 */
  videoW: number
  videoH: number
}

/** 字幕轨（mpv/libass）；id<=0 表示「关闭字幕」 */
export interface SubtitleTrack {
  id: number
  title: string
  lang: string
  selected: boolean
}

export interface AudioDevice {
  deviceId: string
  label: string
}

export interface SubStyle {
  font?: string
  fontSize?: number
  color?: string
  borderColor?: string
  borderSize?: number
  shadowOffset?: number
  pos?: number
  /** 背景条基色 #RRGGBB（P0-24）；与 backOpacity 一起由 Rust 合成 mpv 的 #AARRGGBB */
  backColor?: string
  /** 背景条不透明度 0–100，0 = 无背景条（mpv 默认） */
  backOpacity?: number
  /** mpv sub-ass-override（P0-25）：no | yes | force | scale | strip */
  assOverride?: AssOverride
}

/** `sub-ass-override` 的五个合法档位（顺序即 UI 展示顺序） */
export type AssOverride = 'no' | 'yes' | 'force' | 'scale' | 'strip'

// ── ffmpeg 任务 ─────────────────────────────────────────────

export interface FfmpegInfo {
  available: boolean
  path: string | null
  version: string | null
}

/** Rust: `fftools::ExecResult` */
export interface ExecResult {
  code: number
  stdout: string | null
  stderr: string | null
  error: string | null
}

export interface ConvertItem {
  id: number
  path: string
  outPath: string
  kind: 'convert' | 'extract'
  format: string
}

export interface ConvertProgress {
  taskId: number
  itemId: number
  state: 'running' | 'done' | 'failed' | 'cancelled' | 'queue-finished'
  error?: string
}

// ── 外观 ────────────────────────────────────────────────────

export interface BgImageData {
  path: string
  mtime?: number
}

// ── AI ──────────────────────────────────────────────────────

export interface ChatMessage {
  role: string
  content: string
}

export interface AiChatPayload {
  baseUrl: string
  apiKey: string
  model: string
  /** `ai_ping` 不需要它（Rust 侧 `#[serde(default)]`），由后端补一条最小请求 */
  messages?: ChatMessage[]
  temperature?: number
}

export interface AiChatResult {
  ok: boolean
  content: string
  error?: string
}

export interface AiPingResult {
  ok: boolean
  message: string
  /** 以下三项由 AI-5 的连通性测试回显；失败时 Rust 侧整键缺席（camelCase，见 model.rs） */
  model?: string
  latencyMs?: number
  totalTokens?: number
}

export interface AiModelsResult {
  ok: boolean
  models: string[]
  error?: string
}
